# Nombre de la aplicación
spring.application.name=medicore-server
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Puerto de salida
server.port=8080

# Banner de log
spring.main.log-startup-info=true