ALTER TABLE medico DROP CONSTRAINT IF EXISTS fk_medico_usuario;
ALTER TABLE paciente DROP CONSTRAINT IF EXISTS fk_paciente_usuario;

DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS rol_usuario;

ALTER TABLE paciente RENAME TO usuario;

ALTER TABLE usuario ADD COLUMN IF NOT EXISTS estado boolean NOT NULL DEFAULT true;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS rol varchar(20) NOT NULL DEFAULT 'PACIENTE';

ALTER TABLE usuario DROP CONSTRAINT IF EXISTS chk_usuario_rol;
ALTER TABLE usuario ADD CONSTRAINT chk_usuario_rol
    CHECK (rol IN ('PACIENTE', 'ADMIN'));

ALTER TABLE cita ALTER COLUMN estado TYPE varchar(20);
ALTER TABLE cita ALTER COLUMN estado SET DEFAULT 'PENDIENTE';

UPDATE cita SET estado = 'PENDIENTE'
WHERE estado NOT IN ('APROBADA', 'PENDIENTE', 'DENEGADA');

ALTER TABLE cita DROP CONSTRAINT IF EXISTS chk_cita_estado;
ALTER TABLE cita ADD CONSTRAINT chk_cita_estado
    CHECK (estado IN ('APROBADA', 'PENDIENTE', 'DENEGADA'));